default: &default
  adapter: mysql2
  encoding: utf8mb4
  charaset: utf8mb4
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
